### ISSUE TITLE
Repl refers to "Babel 6.24.2" which doesn't exist

### ISSUE THREAD

**Issue by also** [babel/website#1255] opened 2017-05-18 20:01 UTC
I assumed that the Babel version shown in the repl would be a released version of `babel-cli` or `babel-core`, but the most recent v6 tag is `v6.24.1`.

This made it confusing to try and replicate an issue with the Node.js version of Babel using the repl, because it appears that the repl uses an unreleased version of Babel.

It appears from https://github.com/babel/babel.github.io/issues/1248 that the version displayed is from babel-standalone, but this isn't obvious and I expect not what most people would assume.

**Comment by ashsearle** [comment] 2017-05-27 11:07
I see the Babel version displayed is consistent with the console (`window.Babel.version`)

babili also comes in as a standalone package (currently from `https://unpkg.com/babili-standalone@0.0.10/babili.min.js`), but the version number found through the console is different (i.e. `window.Babili.version` currently shows `0.0.9`, which is really old.)

As @also says, this is confusing and makes it difficult to make valid reproducible minimal test cases.

**Comment by Daniel15** [comment] 2017-06-05 07:10
Sorry about that... I had to hotfix babel-standalone to patch https://github.com/babel/babel-standalone/issues/84. The version number would have been something like `6.24.1.1` but unfortunately babel-standalone is an npm package and thus is restricted to using semver-compatible version numbers.

**Comment by ashsearle** [comment] 2017-06-05 07:50
I guess there's no way to rule-out this happening again, so wonder if babel/babel-standalone#59 should be revisited to make it work as described: determining the displayed babel version number from the compiled dependencies, instead of from babel-standalone's own `package.json`?

**Comment by Daniel15** [comment] 2017-06-05 08:06
https://github.com/babel/babel-standalone/issues/59 is normally how it works, but it doesn't account for the case where patches need to be applied in between Babel releases. Unfortunately semver has no concept of upstream versions 😢 

I could make `Babel.version` just contain the Babel version, but then `Babel.version` having a different version number to the `babel-standalone` package might be confusing. 

Alternatively I could have an array of Babel package versions (like `Babel.versions['babel-core']` for `babel-core`, etc). Do you think that would be a good idea?

The original version numbering scheme of babel-standalone was to have totally separate version numbers (eg. babel-standalone 1.0.0 included Babel 6.3.13) but that's way more confusing.

**Comment by ashsearle** [comment] 2017-06-05 08:19
Focussing on the reason this issue was raised (confusion about version number displayed in the online REPL), perhaps the simplest solution is just to change the displayed version from:

Babel 6.24.2

To:

Babel (standalone) 6.24.2 ?

**Comment by hzoo** [comment] 2017-08-08 22:03
we could do that, we also have a pr now to move it into the repo https://github.com/babel/babel/pull/6029 so it would have the same version number

**Comment by hzoo** [comment] 2017-08-29 16:01
Should be fixed now with the new repl

**Closed by hzoo** 2017-08-29 16:01 UTC
