### ISSUE TITLE
No slash ended url will redirect to error!

### ISSUE THREAD

**Issue by minseclab** [babel/website#1706] opened 2018-06-24 12:35 UTC
Where visit the site with no slash ended url "https://babeljs.io/docs/en", then the foot next button doesn't work well.

**Comment by hzoo** [comment] 2018-06-25 02:05
Duplicate of https://github.com/babel/website/issues/1693

Thanks for reporting but closing in favor of ^, should be fixed if we update Docusaurus

**Closed by hzoo** 2018-06-25 02:05 UTC
