### ISSUE TITLE
REPL throwing TypeError

### ISSUE THREAD

**Issue by atelljohannsmothers** [babel/website#1422] opened 2017-10-16 11:50 UTC
https://babeljs.io/repl/ is throwing the error below:
```
react-dom.production.min.js:23 TypeError: document.body.append is not a function(…)
```

**Comment by xtuc** [comment] 2017-10-16 13:11
Interesting, I don't have this issue on my side (even after cleaning the cache).

Can you see the REPL? Could you retry after cleaning your cache?

**Comment by rajzshkr** [comment] 2017-10-25 12:29
it works for me too.

**Comment by joosebox** [comment] 2017-10-26 04:39
Not sure if this is related, but I clicked "Try" on the JavaScript block of code in the "JSX and Flow" section of the homepage. Here's the [REPL](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Cstage-0%2Creact&code=export%20default%20React.createClass(%7B%0A%20%20getInitialState()%20%7B%0A%20%20%20%20return%20%7B%20num%3A%20this.getRandomNumber()%20%7D%3B%0A%20%20%7D%2C%0A%0A%20%20getRandomNumber()%3A%20number%20%7B%0A%20%20%20%20return%20Math.ceil(Math.random()%20*%206)%3B%0A%20%20%7D%2C%0A%0A%20%20render()%3A%20any%20%7B%0A%20%20%20%20return%20%3Cdiv%3E%0A%20%20%20%20%20%20Your%20dice%20roll%3A%0A%20%20%20%20%20%20%7Bthis.state.num%7D%0A%20%20%20%20%3C%2Fdiv%3E%3B%0A%20%20%7D%0A%7D)%3B).

I'm getting this error without making any modifications to the sample:
repl: Unexpected token, expected { (6:19)
  4 |   },
  5 | 
> 6 |   getRandomNumber(): number {
    |                    ^
  7 |     return Math.ceil(Math.random() * 6);
  8 |   },
  9 |

**Comment by existentialism** [comment] 2017-10-26 04:42
@joosebox thanks for the report! that issue (though unrelated) should now be fixed!

**Comment by joosebox** [comment] 2017-10-26 04:54
@existentialism well that was fast! awesome! :)

mind letting me know what the problem was? curiosity is getting the best of me. thanks in advance!

**Comment by existentialism** [comment] 2017-10-26 04:54
@joosebox landed https://github.com/babel/website/pull/1434, which fixed a bug caused by a recent PR!

**Closed** 2017-11-14 15:49 UTC
Labels: bug, repl
