### ISSUE TITLE
Broken PREVIOUS/NEXT links for polyfill and register on runtime generators page

### ISSUE THREAD

**Issue by roschler** [babel/website#1693] opened 2018-06-14 17:06 UTC
On this page, the PREVIOUS/NEXT links for BABEL-POLYFILL and BABEL-REGISTER are broken (404 errors).  I'm referring to the two links at the bottom of the page, not the ones in the sidebar(s):

https://babeljs.io/docs/en/babel-plugin-transform-runtime/

Here are the URLs for the broken links:

https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-polyfill.html
https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register.html

Here the links for those same destination pages taken from the sidebar equivalent links, which do work:

https://babeljs.io/docs/en/babel-polyfill.html
https://babeljs.io/docs/en/babel-register.html

It looks like there is some bad template expansion code somewhere that is adding the _current page name_, "babel-plugin-transform" in this instance, to the PREVIOUS/NEXT links in some cases.  Therefore, it may be happening on a lot more pages than this one.

**Comment by microbouji** [comment] 2018-06-14 20:44
It seems to be happening when the link ends in `/` rather than `.html`

So prev/next links are broken e.g. in https://babeljs.io/docs/en/babel-polyfill/, but not in https://babeljs.io/docs/en/babel-polyfill.html

**Comment by hzoo** [comment] 2018-06-15 14:55
Is this a docusaurus issue? @JoelMarcey

**Comment by JoelMarcey** [comment] 2018-06-15 16:57
Hi @hzoo @microbouji -- possibly. What version of Docusaurus are you running?

**Comment by hzoo** [comment] 2018-06-15 17:02
Looks like 1.1.5 now!

Oh I see https://github.com/facebook/Docusaurus/releases/tag/v1.2.0

Looks like https://github.com/facebook/Docusaurus/commit/31f0c27f81ac9d22f8fdd29f5265e60b5b038773 is the option. `cleanUrl` which is good to see?

**Comment by JoelMarcey** [comment] 2018-06-15 17:04
Yeah, we enabled extension-less URLs in 1.2.0. Maybe that would fix your issue here?

**Comment by JoelMarcey** [comment] 2018-06-15 17:04
> So looks like the solution is to update and add that option?

🤞

**Comment by JoelMarcey** [comment] 2018-06-15 17:08
Definitely test locally before pushing, of course 😄

**Comment by hzoo** [comment] 2018-06-15 18:09
`https://babeljs.io/docs/en/babel-plugin-transform-runtime` works fine too actually. it's just when there is a trailing slash `/` whether or not docusaurus is updated.

**Comment by JoelMarcey** [comment] 2018-06-15 18:17
> https://babeljs.io/docs/en/babel-plugin-transform-runtime works fine too actually. it's just when there is a trailing slash / whether or not docusaurus is updated.

That may be an unknown bug then. We need to investigate. Might just be a small logic bug we have. Can you remove the trailing slash for now? Or would that be too hard?

> Also funny seeing the same issue as facebook/Docusaurus#759 😄

Did you clear the Babel cache? 😆 https://docusaurus.io/docs/en/next/installation#updating-your-docusaurus-version

**Comment by endiliey** [comment] 2018-06-16 08:13
Hi ✋,

This is actually caused by how relative path in href works.

In `https://babeljs.io/docs/en/babel-plugin-transform-runtime`
href of `babel-register` will translate to `https://babeljs.io/docs/en/babel-register`

In `https://babeljs.io/docs/en/babel-plugin-transform-runtime/`
href of `babel-register` will translate to `https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register`

**Comment by endiliey** [comment] 2018-06-17 03:44
Hi ✋,

FYI. This is fixed on https://github.com/facebook/Docusaurus/pull/783

**Comment by hzoo** [comment] 2018-06-25 02:06
Anyone want to make a PR to update (looks like there are css changes in the update so need to check that too (can do screenshots or use the preview url)

**Closed** 2018-07-02 13:40 UTC
Labels: help wanted
